Repository clapsheep/honeyboard-client, pull requests merged in 2024-12, with the labels that each got.

#1 [markup] Button, NameTag 컴포넌트 제작
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/NameTag/NameTag.stories.tsx
  src/components/atoms/NameTag/NameTag.tsx
  src/components/molecules/index.ts
  src/components/organisms/index.ts
  src/components/templates/index.ts
Labels: 🎨 Markup

#15 [markup] Input 관련 컴포넌트 마크업
  .github/ISSUE_TEMPLATE/마크업-이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/atoms/ErrorMessage/ErrorMessage.stories.tsx
  src/components/atoms/ErrorMessage/ErrorMessage.tsx
  src/components/atoms/Input/Input.stories.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Label/Label.stories.tsx
  src/components/atoms/Label/Label.tsx
  src/components/atoms/index.ts
Labels: 🎨 Markup

#23 [markup] CalendarTag 컴포넌트 제작
  src/components/atoms/CalendarTag/CalendarTag.stories.tsx
  src/components/atoms/CalendarTag/CalendarTag.tsx
  src/components/atoms/index.ts
Labels: 🎨 Markup

#28 [init] svg 아이콘 수정, 추가
  src/assets/icons/_sprite.svg
  src/assets/icons/back-arrow.svg
  src/assets/icons/ball.svg
  src/assets/icons/button-search.svg
  src/assets/icons/cancle-circle.svg
  src/assets/icons/checkbox-checked.svg
  src/assets/icons/checkbox-default.svg
  src/assets/icons/crown.svg
  src/assets/icons/down.svg
  src/assets/icons/edit-user.svg
  src/assets/icons/google-icon.svg
  src/assets/icons/leader.svg
  src/assets/icons/left.svg
  src/assets/icons/music.svg
  src/assets/icons/naver-icon.svg
  src/assets/icons/radio-off.svg
  src/assets/icons/radio-on.svg
  src/assets/icons/right.svg
  src/assets/icons/search.svg
  src/assets/icons/send.svg
  src/assets/icons/sound.svg
  src/assets/icons/star-empty.svg
  src/assets/icons/star.svg
  src/assets/icons/trashcan.svg
  src/assets/icons/up.svg
  src/components/atoms/NameTag/NameTag.tsx
Labels: ⚙️ Setting

#46 [markup] ProjectCard 컴포넌트 제작
  src/components/organisms/ProjectCard/ProjectCard.stories.tsx
  src/components/organisms/ProjectCard/ProjectCard.tsx
  src/components/organisms/index.ts
Labels: 🎨 Markup

#26 [markup] ButtonPDF, TeamTag 컴포넌트 및 스토리북 제작
  src/components/atoms/ButtonPDF/ButtonPDF.stories.tsx
  src/components/atoms/ButtonPDF/ButtonPDF.tsx
  src/components/atoms/TeamTag/TeamTag.stories.tsx
  src/components/atoms/TeamTag/TeamTag.tsx
  src/components/atoms/index.ts
Labels: 🎨 Markup

#52 [fix, markup] Input, InputForm 컴포넌트 수정/WebSiteCard 컴포넌트 제작
  src/assets/icons/star-empty.svg
  src/assets/icons/star.svg
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Input/Input.stories.tsx
  src/components/atoms/Input/Input.tsx
  src/components/molecules/InputForm/InputForm.stories.tsx
  src/components/molecules/InputForm/InputForm.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.stories.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.tsx
  src/components/molecules/index.ts
Labels: 🛠️ Refactor, 🎨 Markup

#54 [markup] Chat 컴포넌트 제작
  src/assets/icons/caution.svg
  src/assets/icons/pagination-arrow-left.svg
  src/assets/icons/pagination-arrow-right.svg
  src/assets/icons/warning.svg
  src/components/atoms/Chat/Chat.stories.tsx
  src/components/atoms/Chat/Chat.tsx
Labels: 🎨 Markup

#57 [reafactor] ProjectCard, WebSiteCard, Input 컴포넌트 리팩토링
  src/assets/icons/search.svg
  src/components/atoms/Input/Input.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.stories.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.tsx
  src/components/organisms/ProjectCard/ProjectCard.stories.tsx
  src/components/organisms/ProjectCard/ProjectCard.tsx
Labels: 🛠️ Refactor, 🎨 Markup

#55 [markup] 컴포넌트 마크업 및 기존 컴포넌트 리팩토링
  .storybook/preview.ts
  src/assets/images/bojIcon.png
  src/assets/images/programmersIcon.png
  src/assets/images/sweaIcon.png
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/ButtonPDF/ButtonPDF.stories.tsx
  src/components/atoms/CalendarTag/CalendarTag.stories.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/NameTag/NameTag.tsx
  src/components/atoms/SelectOption/SelectOption.stories.tsx
  src/components/atoms/SelectOption/SelectOption.tsx
  src/components/atoms/SocialLoginButton/SocialLoginButton.stories.tsx
  src/components/molecules/AlgoProblemCard/AlgoProblemCard.stories.tsx
  src/components/molecules/AlgoProblemCard/AlgoProblemCard.tsx
  src/components/molecules/InputForm/InputForm.stories.tsx
  src/components/molecules/TeamTag/TeamTag.stories.tsx
  src/components/molecules/TeamTag/TeamTag.tsx
  src/components/molecules/YoutubeCard/YoutubeCard.stories.tsx
  src/components/molecules/YoutubeCard/YoutubeCard.tsx
  src/components/molecules/index.ts
  src/components/organisms/ProjectCard/ProjectCard.tsx
  src/utils/getPlatformInfo.ts
Labels: 🛠️ Refactor, 🎨 Markup

#50 [markup] SelectForInput, SubNavButton, ModalButton 컴포넌트 구현 및 수정
  package-lock.json
  package.json
  src/components/atoms/ModalButton/ModalButton.stories.tsx
  src/components/atoms/ModalButton/ModalButton.tsx
  src/components/atoms/SearchDropDown/SearchDropDown.tsx
  src/components/atoms/SelectForInput/SelectForInput.stories.tsx
  src/components/atoms/SelectForInput/SelectForInput.tsx
  src/components/atoms/SubNavButton/SubNavButton.stories.tsx
  src/components/atoms/SubNavButton/SubNavButton.tsx
  src/components/atoms/index.ts
Labels: 🎨 Markup

#59 [markup] AlgoDetailCard, ChatInput, MusicTrack 컴포넌트 제작
  src/assets/icons/send.svg
  src/components/atoms/ChatInput/ChatInput.stories.tsx
  src/components/atoms/ChatInput/ChatInput.tsx
  src/components/atoms/index.ts
  src/components/molecules/AlgoDetailCard/AlgoDetailCard.stories.tsx
  src/components/molecules/AlgoDetailCard/AlgoDetailCard.tsx
  src/components/molecules/MusicTrack/MusicTrack.stories.tsx
  src/components/molecules/MusicTrack/MusicTrack.tsx
  src/components/molecules/index.ts
  src/components/organisms/ProjectCard/ProjectCard.tsx
Labels: 🎨 Markup

#60 [markup] StudentInfo 컴포넌트 제작
  src/components/atoms/index.ts
  src/components/molecules/StudentInfo/StudentInfo.stories.tsx
  src/components/molecules/StudentInfo/StudentInfo.tsx
  src/components/molecules/index.ts
Labels: 🎨 Markup

#70 [feat] 로그인, 회원가입 기능 및 마크업, 라우팅 구현
  index.html
  src/App.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/ModalButton/ModalButton.tsx
  src/components/atoms/NameTag/NameTag.stories.tsx
  src/components/atoms/index.ts
  src/components/molecules/InputForm/InputForm.tsx
  src/components/molecules/index.ts
  src/components/organisms/EmailVerificationModal/EmailVerificationModal.stories.tsx
  src/components/organisms/EmailVerificationModal/EmailVerificationModal.tsx
  src/components/organisms/index.ts
  src/layouts/MainLayout.tsx
  src/main.tsx
  src/pages/AdditionalInfoOAuth.tsx
  src/pages/Error404.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/pages/index.tsx
  src/services/auth/authAPI.ts
  src/services/auth/authService.ts
  src/services/auth/index.ts
  src/types/auth/index.ts
  src/types/auth/schema.ts
  src/types/auth/types.ts
Labels: 🚧 Feature, 🛠️ Refactor, 🎨 Markup

#68 [markup] SearchDropDown 컴포넌트 구현, 리팩토링
  src/components/atoms/SearchDropDown/SearchDropDown.stories.tsx
  src/components/atoms/SearchDropDown/SearchDropDown.tsx
  src/components/atoms/index.ts
  src/components/organisms/BasicModal/BasicModal.tsx
Labels: 🛠️ Refactor, 🎨 Markup

#75 [refactor] Navigation 연결, 이미지 경로 수정
  public/assets/icons/_sprite.svg
  public/assets/icons/back-arrow.svg
  public/assets/icons/ball.svg
  public/assets/icons/button-search.svg
  public/assets/icons/calendar.svg
  public/assets/icons/cancle-circle.svg
  public/assets/icons/caution.svg
  public/assets/icons/checkbox-checked.svg
  public/assets/icons/checkbox-default.svg
  public/assets/icons/circle-close-red.svg
  public/assets/icons/document.svg
  public/assets/icons/down.svg
  public/assets/icons/edit-user.svg
  public/assets/icons/google-icon.svg
  public/assets/icons/leader.svg
  public/assets/icons/left.svg
  public/assets/icons/music.svg
  public/assets/icons/naver-icon.svg
  public/assets/icons/pagination-arrow-left.svg
  public/assets/icons/pagination-arrow-right.svg
  public/assets/icons/pen.svg
  public/assets/icons/radio-off.svg
  public/assets/icons/radio-on.svg
  public/assets/icons/right.svg
  public/assets/icons/search.svg
  public/assets/icons/send.svg
  public/assets/icons/sound.svg
  public/assets/icons/star-empty.svg
  public/assets/icons/star.svg
  public/assets/icons/trashcan.svg
  public/assets/icons/up.svg
  public/assets/icons/user.svg
  public/assets/icons/warning.svg
  public/assets/images/bojIcon.png
  public/assets/images/logo.png
  public/assets/images/programmersIcon.png
  public/assets/images/sweaIcon.png
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/index.ts
  src/components/molecules/NavMenu/NavMenu.tsx
  src/components/organisms/Navigation/Navigation.tsx
  src/layouts/MainLayout.tsx
  src/pages/AdditionalInfoOAuth.tsx
  src/pages/Error404.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/utils/getPlatformInfo.ts
Labels: 🛠️ Refactor

#79 [refactor] 로그인(OAuth, 일반), 로그아웃 기능 구현 확인
  index.html
  public/favicon.ico
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Input/Input.tsx
  src/components/organisms/Navigation/Navigation.tsx
  src/hooks/useSignUp.ts
  src/pages/AdditionalInfoOAuth.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/services/auth/authAPI.ts
  src/services/auth/authService.ts
  src/services/common/axiosInstance.ts
  src/stores/userStore.ts
  src/types/auth/schema.ts
  src/types/auth/types.ts
  tsconfig.app.json
  tsconfig.node.json
Labels: 🛠️ Refactor

#80 [markup] BasicModal 컴포넌트 구현
  src/components/organisms/BasicModal/BasicModal.stories.tsx
  src/components/organisms/BasicModal/BasicModal.tsx
  src/components/organisms/index.ts
Labels: 🎨 Markup

#69 [refactor] ChatInput 컴포넌트 리팩토링
  src/components/atoms/ChatInput/ChatInput.stories.tsx
  src/components/atoms/ChatInput/ChatInput.tsx
Labels: 🛠️ Refactor, 🎨 Markup

#82 [feat] 채팅기능구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/organisms/Navigation/Navigation.tsx
  src/hooks/useChat.ts
  src/layouts/MainLayout.tsx
  src/layouts/PrivateRoute.tsx
  src/pages/AdditionalInfoOAuth.tsx
  src/pages/Login.tsx
  src/pages/LoginCallback.tsx
  src/pages/PlayList.tsx
  src/pages/index.tsx
  src/services/auth/authAPI.ts
  src/services/auth/authService.ts
  src/services/auth/index.ts
  src/services/chat/chatAPI.ts
  src/services/chat/chatService.ts
  src/services/chat/index.ts
  src/stores/userStore.ts
  src/types/chat/index.ts
  src/types/chat/types.ts
  src/types/common/type.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🚧 Feature

#83 [refactor]: Navigation 에러 수정, NavMenu 커스텀 훅 분리
  src/components/atoms/NavButton/NavButton.tsx
  src/components/molecules/NavMenu/NavMenu.tsx
  src/components/organisms/Navigation/NavItem.ts
  src/components/organisms/Navigation/Navigation.tsx
  src/hooks/useNavigationItems.tsx
Labels: 🛠️ Refactor

#74 [markup] StudentList 컴포넌트 제작
  src/components/molecules/StudentInfo/StudentInfo.tsx
  src/components/organisms/StudentList/StudentList.stories.tsx
  src/components/organisms/StudentList/StudentList.tsx
Labels: 🛠️ Refactor, 🎨 Markup

#78 [markup] ChatBox organism 제작, Chat수정, InputForm ml-1 추가 - 수정
  src/components/atoms/Chat/Chat.tsx
  src/components/atoms/index.ts
  src/components/molecules/InputForm/InputForm.tsx
  src/components/organisms/ChatBox/ChatBox.stories.tsx
  src/components/organisms/ChatBox/ChatBox.tsx
  src/index.css
Labels: 🎨 Markup

#100 [feat] Header 컴포넌트 제작
  src/App.tsx
  src/components/atoms/TabButton/TabButton.tsx
  src/components/molecules/Breadcrumb/Breadcrumb.stories.tsx
  src/components/molecules/Breadcrumb/Breadcrumb.tsx
  src/components/molecules/InputForm/InputForm.tsx
  src/components/molecules/TabNavigation/TabNavigation.stories.tsx
  src/components/molecules/TabNavigation/TabNavigation.tsx
  src/components/molecules/Title/Title.tsx
  src/components/molecules/index.ts
  src/components/organisms/ChatBox/ChatBox.stories.tsx
  src/components/organisms/Header/Header.stories.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Navigation/NavItem.ts
  src/components/organisms/Navigation/Navigation.stories.tsx
  src/components/organisms/StudentList/StudentList.stories.tsx
  src/components/organisms/index.ts
  src/layouts/MainLayout.tsx
  src/layouts/PrivateRoute.tsx
  src/pages/LoginCallback.tsx
  src/pages/index.tsx
  src/pages/music/PlayList.tsx
  src/pages/project/final/FinalList.tsx
  src/pages/project/track/TrackList.tsx
  src/pages/study/algorithm/AlgorithmConceptList.tsx
  src/pages/study/algorithm/AlgorithmProblem.tsx
  src/pages/study/web/WebConceptList.tsx
  src/pages/study/web/WebRecommendList.tsx
  src/utils/calcRouteStructure.ts
Labels: 🚧 Feature, 🎨 Markup

#101 [refactor] 라우팅 수정 및 페이지 헤더 작성
  src/App.tsx
  src/components/molecules/Breadcrumb/Breadcrumb.stories.tsx
  src/components/organisms/Header/Header.stories.tsx
  src/pages/index.tsx
  src/pages/project/final/CreateFinalTeam.tsx
  src/pages/project/final/FinalList.tsx
  src/pages/project/track/CreateTrackProject.tsx
  src/pages/project/track/TrackList.tsx
  src/pages/study/algorithm/AlgorithmConceptList.tsx
  src/pages/study/algorithm/AlgorithmProblemList.tsx
  src/pages/study/algorithm/CreateAlgorithmConcept.tsx
  src/pages/study/algorithm/CreateAlgorithmProblem.tsx
  src/pages/study/algorithm/CreateAlgorithmProblemSolution.tsx
  src/pages/study/web/CreateWebConcept.tsx
  src/pages/study/web/CreateWebRecommend.tsx
  src/utils/calcRouteStructure.ts
Labels: 🛠️ Refactor

#103 [feat] 웹 개념, 웹 추천 리스트 페이지 마크업 및 기능 구현
  src/components/atoms/SelectOption/SelectOption.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.stories.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.tsx
  src/components/molecules/WebSiteCard/WebSiteCardSkeleton.tsx
  src/components/molecules/index.ts
  src/components/organisms/ProjectCard/ProjectCard.stories.tsx
  src/components/organisms/ProjectCard/ProjectCard.tsx
  src/components/organisms/ProjectCard/ProjectCardSkeleton.tsx
  src/components/organisms/index.ts
  src/components/templates/Skeletons/ProjectCardSkeletonList.tsx
  src/components/templates/Skeletons/WebSiteCardSkeletonList.tsx
  src/components/templates/WebConceptCards.tsx
  src/components/templates/WebRecommendCards.tsx
  src/components/templates/index.ts
  src/pages/project/final/FinalList.tsx
  src/pages/project/track/TrackList.tsx
  src/pages/study/algorithm/AlgorithmConceptList.tsx
  src/pages/study/web/WebConceptList.tsx
  src/pages/study/web/WebRecommendList.tsx
  src/services/study/algorithm/algorithmAPI.ts
  src/services/study/algorithm/index.ts
  src/services/study/web/index.ts
  src/services/study/web/type.ts
  src/services/study/web/webAPI.ts
Labels: 🚧 Feature
