Repository clapsheep/honeyboard-client, pull requests merged in 2025-02, with the labels that each got.

#231 [refator] 회원가입 추가정보 입력시 이동 안하는 문제 해결, 이메일 인증 요청 중복해서 못보내게 해결
  src/hooks/useSignUp.ts
  src/pages/AdditionalInfoOAuth.tsx
  src/pages/SignUp.tsx
Labels: 🛠️ Refactor

#232 [refator] 회원가입 추가정보 입력시 이동 안하는 문제 해결, 이메일 인증 요청 중복해서 못보내게 해결
  src/hooks/useSignUp.ts
  src/pages/AdditionalInfoOAuth.tsx
  src/pages/SignUp.tsx
Labels: 🌎 Deploy

#233 [refactor] 유튜브 재생시 콘솔 에러 수정, 노래 빈칸 검색 시 검색어 입력 안내 닫기 수정
  src/components/organisms/PlayListSection/PlayListSection.tsx
  src/pages/music/SearchMusic.tsx
Labels: 🛠️ Refactor

#234 [refactor] 유튜브 재생시 콘솔 에러 수정, 노래 빈칸 검색 시 검색어 입력 안내 닫기 수정
  src/components/organisms/PlayListSection/PlayListSection.tsx
  src/pages/music/SearchMusic.tsx
Labels: 🌎 Deploy, 🛠️ Refactor

#235 [fix] 알고리즘 생성 에러 수정
  src/components/atoms/Input/Input.tsx
Labels: ❌ Bug

#236 [refactor] 파이널 프로젝트 삭제 api 경로 변경
  src/api/finaleAPI.ts
  src/pages/finalProject/FinalProjectBoardDetail.tsx
  src/pages/finalProject/FinalProjectDetail.tsx
Labels: 🛠️ Refactor

#238 [fix] 피날레 게시글 등록 오류, 웹추천 중복 url 오류 해결
  src/api/finaleAPI.ts
  src/components/molecules/TeamTag/TeamTag.tsx
  src/pages/finalProject/FinalProjectBoardCreate.tsx
  src/pages/webRecommend/WebRecommendCreate.tsx
  src/pages/webRecommend/WebRecommendUpdate.tsx
Labels: ❌ Bug

#240 [fix] : FinaleProject, TrackProject 모달창과 팀에 대한 수정
  src/components/templates/FinaleProjectTeam.tsx
  src/components/templates/TrackProject.tsx
  src/components/templates/TrackProjectTeam.tsx
  src/hooks/useFinaleProject.ts
  src/pages/finalProject/FinalProjectCreate.tsx
  src/pages/finalProject/FinalProjectUpdate.tsx
  src/pages/trackProject/TrackProjectTeamCreate.tsx
  src/pages/trackProject/TrackProjectTeamUpdate.tsx
Labels: ❌ Bug
