Repository clapsheep/honeyboard-client, pull requests merged in 2025-01, with the labels that each got.

#104 [feat] 웹 개념 디테일 페이지 마크업 및 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.stories.tsx
  src/components/organisms/BasicModal/BasicModal.tsx
  src/components/organisms/Navigation/Navigation.tsx
  src/components/organisms/ProjectCard/ProjectCard.stories.tsx
  src/components/templates/WebConceptCards.tsx
  src/hooks/useContentDetail.ts
  src/hooks/useToastViewer.ts
  src/index.css
  src/layouts/ToastViewerComponent.tsx
  src/pages/index.tsx
  src/pages/study/web/WebConceptDetail.tsx
  src/pages/study/web/WebRecommendDetail.tsx
  src/services/study/web/type.ts
  src/services/study/web/webAPI.ts
  src/services/user/index.ts
  src/services/user/types.ts
  src/services/user/userAPI.ts
  src/stores/modalStore.ts
  src/types/toast-ui.d.ts
Labels: 🚧 Feature

#105 [markup] Schedule 페이지 마크업
  package-lock.json
  package.json
  src/App.tsx
  src/hooks/useSchedule.ts
  src/hooks/useScheduleEvents.ts
  src/pages/Schedule.tsx
  src/pages/index.tsx
  src/services/schedule/index.ts
  src/services/schedule/scheduleAPI.ts
  src/types/schedule/index.ts
  src/types/schedule/types.ts
Labels: 🚧 Feature, 🎨 Markup

#106 [feat] 알고리즘 문제풀이 리스트 페이지 마크업 및 기능 구현
  src/components/molecules/AlgoProblemCard/AlgoProblemCard.tsx
  src/components/molecules/AlgoProblemCard/AlgoProblemCardSkeleton.tsx
  src/components/molecules/index.ts
  src/components/templates/AlgoProblemCards.tsx
  src/components/templates/Skeletons/AlgoProblemCardSkeletonList.tsx
  src/components/templates/index.ts
  src/pages/study/algorithm/AlgorithmProblemList.tsx
  src/services/study/algorithm/algorithmAPI.ts
  src/services/study/algorithm/type.ts
Labels: 🚧 Feature, 🎨 Markup

#107 [feat] Editor 컴포넌트 제작 및 기능 구현 / 웹 개념 작성 페이지 구현
  package-lock.json
  src/hooks/useToastEditor.ts
  src/layouts/ToastEditorComponent.tsx
  src/pages/study/web/CreateWebConcept.tsx
  src/services/image/imageAPI.ts
  src/services/study/web/type.ts
  src/services/study/web/webAPI.ts
  src/types/image/types.ts
  src/utils/imageOptimization/analyze.ts
  src/utils/imageOptimization/index.ts
  src/utils/imageOptimization/optimize.ts
  src/utils/imageOptimization/types.ts
Labels: 🚧 Feature, 🎨 Markup

#109 [markup] SearchBar, SearchTeamMember 컴포넌트 제작, 파이널 페이지 마크업 중
  public/assets/icons/_sprite.svg
  public/assets/icons/white-search.svg
  src/components/atoms/Button/Button.tsx
  src/components/atoms/SearchDropDown/SearchDropDown.tsx
  src/components/molecules/SearchBar/SearchBar.stories.tsx
  src/components/molecules/SearchBar/SearchBar.tsx
  src/components/molecules/index.ts
  src/components/organisms/SearchTeamMember/SearchTeamMember.stories.tsx
  src/components/organisms/SearchTeamMember/SearchTeamMember.tsx
  src/hooks/useFinaleBoard.ts
  src/pages/project/final/CreateFinalTeam.tsx
  src/services/project/finale/finaleAPI.ts
  src/services/project/finale/finaleService.ts
  src/services/project/finale/index.ts
  src/types/project/finale/index.ts
  src/types/project/finale/types.ts
Labels: 🎨 Markup

#110 [feat] 기수관리, 학생관리 ADMIN 페이지 마크업 및 기능 구현
  package-lock.json
  public/assets/loading/spinner.svg
  src/App.tsx
  src/components/atoms/ChatInput/ChatInput.tsx
  src/components/atoms/Checkbox/Checkbox.stories.tsx
  src/components/atoms/Checkbox/Checkbox.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Label/Label.tsx
  src/components/atoms/ModalButton/ModalButton.tsx
  src/components/atoms/SelectOption/SelectOption.stories.tsx
  src/components/atoms/SelectOption/SelectOption.tsx
  src/components/atoms/TabButton/TabButton.stories.tsx
  src/components/atoms/index.ts
  src/components/molecules/AlgoProblemCard/AlgoProblemCard.stories.tsx
  src/components/molecules/InputForm/InputForm.tsx
  src/components/molecules/StudentInfo/StudentInfo.tsx
  src/components/molecules/StudentInfo/StudentInfoSkeleton.tsx
  src/components/organisms/StudentEditModal/StudentEditModal.stories.tsx
  src/components/organisms/StudentEditModal/StudentEditModal.tsx
  src/components/organisms/StudentList/StudentList.tsx
  src/components/organisms/index.ts
  src/components/templates/Skeletons/StudentInfoSkeletonList.tsx
  src/components/templates/WebConceptCards.tsx
  src/components/templates/WebRecommendCards.tsx
  src/hooks/useContentDetail.ts
  src/hooks/useGeneration.ts
  src/hooks/useStudentEdit.ts
  src/layouts/MainLayout.tsx
  src/pages/admin/GenerationManagement.tsx
  src/pages/admin/StudentManagement.tsx
  src/pages/index.tsx
  src/pages/project/final/FinalList.tsx
  src/pages/project/track/TrackList.tsx
  src/pages/study/algorithm/AlgorithmConceptList.tsx
  src/pages/study/web/WebConceptList.tsx
  src/pages/study/web/WebRecommendList.tsx
  src/services/admin/adminAPI.ts
  src/services/admin/settingGeneration.ts
  src/services/common/generation/generationAPI.ts
  src/services/common/generation/generationService.ts
  src/services/common/generation/index.ts
  src/services/study/web/index.ts
  src/services/study/web/webAPI.ts
  src/services/user/index.ts
  src/services/user/types.ts
  src/services/user/userAPI.ts
  src/stores/generationStore.ts
  src/types/admin/types.ts
  src/types/common/type.ts
  src/types/study/type.ts
  src/utils/convertSelectType.ts
Labels: 🚧 Feature, 🛠️ Refactor, 🎨 Markup

#116 [refactor] useAuth 로직 수정
  src/App.tsx
  src/components/molecules/NavMenu/NavMenu.tsx
  src/components/organisms/Navigation/Navigation.tsx
  src/components/templates/Skeletons/AlgoProblemCardSkeletonList.tsx
  src/components/templates/Skeletons/WebSiteCardSkeletonList.tsx
  src/hooks/useAuth.ts
  src/hooks/useNavigationItems.tsx
  src/layouts/MainLayout.tsx
  src/layouts/PrivateRoute.tsx
  src/services/auth/authAPI.ts
  src/services/auth/authService.ts
  src/utils/calcRouteStructure.ts
Labels: 🛠️ Refactor

#117 [refactor] 자잘한 리팩토링 및 충돌 해결
  src/App.tsx
  src/pages/Login.tsx
  src/pages/project/track/CreateTrackProjectBoard.tsx
  src/pages/project/track/UpdateTrackProjectBoard.tsx
  src/services/auth/authAPI.ts
  src/services/study/algorithm/algorithmAPI.ts
Labels: 🛠️ Refactor

#119 [feat] CreateFinalTeam 기능 추가
  src/hooks/useFinaleBoard.ts
  src/pages/project/final/CreateFinalTeam.tsx
  src/services/project/finale/finaleAPI.ts
  src/services/project/finale/finaleService.ts
  src/types/project/finale/types.ts
Labels: 🚧 Feature

#120 [refactor] 타입 재정의 진행중
  src/components/atoms/SocialLoginButton/SocialLoginButton.tsx
  src/components/organisms/Header/Header.tsx
  src/components/templates/MyAlgorithmList.tsx
  src/components/templates/MyTrackProjectList.tsx
  src/components/templates/index.ts
  src/hooks/useMyPage.ts
  src/pages/mypage/algorithm/MyAlgorithm.tsx
  src/pages/mypage/project/MyTrackProject.tsx
  src/services/bookmark/bookmarkAPI.ts
  src/services/mypage/mypageAPI.ts
  src/types/common/type.ts
  src/types/mypage/types.ts
  src/types/new/ FinaleProject.ts
  src/types/new/AlgorithmGuide.ts
  src/types/new/AlgorithmProblem.ts
  src/types/new/AlgorithmSolution.ts
  src/types/new/Tag.ts
  src/types/new/TrackProject.ts
  src/types/new/User.ts
  src/types/new/WebGuideType.ts
  src/types/new/WebRecommendType.ts
  src/types/project/finale/types.ts
Labels: 🛠️ Refactor

#121 [refactor] 파일명 오류 수정
  src/types/new/FinaleProject.ts
Labels: 🛠️ Refactor

#122 [refactor] 타입 재정의 및 api 함수 셋팅 완료
  package-lock.json
  package.json
  src/api/AlgorithmGuide.ts
  src/api/AlgorithmProblemAPI.ts
  src/api/AlgorithmSolutionAPI.ts
  src/api/WebGuideAPI.ts
  src/api/WebRecommendAPI.ts
  src/api/finaleAPI.ts
  src/api/trackAPI.ts
  src/types/new/AlgorithmProblem.ts
  src/types/new/FinaleProject.ts
  src/types/new/TrackProject.ts
  src/types/new/User.ts
  src/types/new/common.ts
Labels: 🛠️ Refactor

#126 [refactor] VAC 패턴 적용을 위한 Create, Update 페이지 분리 및 WebConcept(Guide) 기능 구현
  src/App.tsx
  src/api/AlgorithmGuideAPI.ts
  src/api/WebGuideAPI.ts
  src/components/templates/WebConceptCards.tsx
  src/components/templates/WebGuideForm.tsx
  src/hooks/useContentDetail.ts
  src/hooks/useContentList.ts
  src/hooks/useCreateWebGuide.tsx
  src/pages/algorithmGuide/AlgorithmGuideCreate.tsx
  src/pages/algorithmGuide/AlgorithmGuideCreateUpdate.tsx
  src/pages/algorithmGuide/AlgorithmGuideUpdate.tsx
  src/pages/algorithmProblem/AlgorithmProblemCreate.tsx
  src/pages/algorithmProblem/AlgorithmProblemCreateUpdate.tsx
  src/pages/algorithmProblem/AlgorithmProblemUpdate.tsx
  src/pages/algorithmSolution/AlgorithmSolutionCreate.tsx
  src/pages/algorithmSolution/AlgorithmSolutionCreateUpdate.tsx
  src/pages/algorithmSolution/AlgorithmSolutionUpdate.tsx
  src/pages/finalProject/FinalProjectBoardCreate.tsx
  src/pages/finalProject/FinalProjectBoardCreateUpdate.tsx
  src/pages/finalProject/FinalProjectBoardUpdate.tsx
  src/pages/index.tsx
  src/pages/trackProject/TrackProjectBoardCreate.tsx
  src/pages/trackProject/TrackProjectBoardCreateUpdate.tsx
  src/pages/trackProject/TrackProjectBoardUpdate.tsx
  src/pages/trackProject/TrackProjectCreate.tsx
  src/pages/trackProject/TrackProjectCreateUpdate.tsx
  src/pages/trackProject/TrackProjectTeamCreate.tsx
  src/pages/trackProject/TrackProjectTeamCreateUpdate.tsx
  src/pages/trackProject/TrackProjectTeamUpdate.tsx
  src/pages/trackProject/TrackProjectUpdate.tsx
  src/pages/webGuide/WebGuideCreate.tsx
  src/pages/webGuide/WebGuideCreateUpdate.tsx
  src/pages/webGuide/WebGuideDetail.tsx
  src/pages/webGuide/WebGuideList.tsx
  src/pages/webGuide/WebGuideUpdate.tsx
  src/pages/webRecommend/WebRecommendCreate.tsx
  src/pages/webRecommend/WebRecommendCreateUpdate.tsx
  src/pages/webRecommend/WebRecommendUpdate.tsx
Labels: 🛠️ Refactor

#130 [feat] 알고리즘 문제 생성, 수정 페이지 구현
  package-lock.json
  src/api/AlgorithmTagAPI.ts
  src/components/molecules/SearchBar/SearchBar.tsx
  src/components/organisms/SearchTeamMember/SearchTeamMember.tsx
  src/components/templates/AlgoProblemForm.tsx
  src/components/templates/WebGuideForm.tsx
  src/hooks/useAlgorithmTag.ts
  src/hooks/useToastEditor.ts
  src/pages/algorithmProblem/AlgorithmProblemCreate.tsx
  src/pages/algorithmProblem/AlgorithmProblemUpdate.tsx
  src/types/AlgorithmProblem.ts
  src/utils/convertSelectType.ts
Labels: 🚧 Feature, 🎨 Markup

#132 [refactor] useContentDetail 훅의 재사용성 개선
  src/components/templates/WebRecommendCards.tsx
  src/hooks/useContentDetail.ts
  src/pages/webGuide/WebGuideDetail.tsx
Labels: 🛠️ Refactor

#131 [feat] 관통 리스트 페이지 구현, SelectOption 수정
  src/api/trackAPI.ts
  src/components/atoms/SelectOption/SelectOption.tsx
  src/pages/trackProject/TrackProjectList.tsx
  src/pages/webGuide/WebGuideList.tsx
Labels: 🚧 Feature, 🛠️ Refactor

#133 [refactor] AlgorithmGuideDetail 컴포넌트에서 useContentDetail 훅 적용 방식 개선
  src/components/templates/WebRecommendForm.tsx
  src/pages/algorithmGuide/AlgorithmGuideDetail.tsx
  src/pages/webRecommend/WebRecommendCreate.tsx
  src/pages/webRecommend/WebRecommendDetail.tsx
  src/pages/webRecommend/WebRecommendList.tsx
Labels: 🛠️ Refactor

#134 [feat] 유튜브 기능 구현 완료 및 채팅 기능 구현중
  src/api/chatAPI.ts
  src/api/youtubeAPI.ts
  src/components/atoms/Chat/Chat.tsx
  src/components/atoms/ChatInput/ChatInput.tsx
  src/components/molecules/MusicTrack/MusicTrack.module.css
  src/components/molecules/MusicTrack/MusicTrack.tsx
  src/components/molecules/MusicTrack/MusicTrackSkeleton.tsx
  src/components/molecules/SearchBar/SearchBar.tsx
  src/components/molecules/YoutubeCard/YoutubeCard.tsx
  src/components/molecules/index.ts
  src/components/organisms/ChatSection/ChatSection.tsx
  src/components/organisms/PlayListSection/PlayListSection.tsx
  src/components/organisms/index.ts
  src/components/templates/Skeletons/MusicTrackSkeletonList.tsx
  src/components/templates/index.ts
  src/hooks/useChat.ts
  src/hooks/useYoutube.ts
  src/pages/LoginCallback.tsx
  src/pages/music/PlayList.tsx
  src/pages/music/SearchMusic.tsx
  tailwind.config.js
Labels: 🚧 Feature

#135 [refactor] useContentDetail 훅 적용 방식 개선, SelectOption 컴포넌트 사용처 props 수정, Cards 컴포넌트 generationId 타입에 null 추가
  src/components/templates/AlgorithmGuideCards.tsx
  src/components/templates/WebRecommendCards.tsx
  src/pages/algorithmGuide/AlgorithmGuideList.tsx
  src/pages/algorithmSolution/AlgorithmSolutionDetail.tsx
  src/pages/webRecommend/WebRecommendList.tsx
Labels: 🛠️ Refactor

#136 [feat] 관통 프로젝트 디테일 페이지 마크업 및 구현
  src/components/molecules/TeamTag/TeamTag.tsx
  src/components/organisms/SubmitSection/SubmitSection.stories.tsx
  src/components/organisms/SubmitSection/SubmitSection.tsx
  src/components/organisms/index.ts
  src/components/templates/TrackProjectCards.tsx
  src/components/templates/index.ts
  src/hooks/useProjectDetail.ts
  src/pages/trackProject/TrackProjectDetail.tsx
  src/pages/webGuide/WebGuideDetail.tsx
  src/types/TrackProject.ts
Labels: 🚧 Feature, 🎨 Markup

#137 feat: 알고리즘 문제 풀이 리스트 페이지 필터링 컴포넌트 마크업
  src/components/molecules/FilterChip/FilterChip.stories.tsx
  src/components/molecules/FilterChip/FilterChip.tsx
  src/components/molecules/index.ts
Labels: 🎨 Markup

#140 [feat] 관통 프로젝트 일지 작성 및 수정 페이지 구현
  src/components/atoms/ButtonPDF/ButtonPDF.tsx
  src/components/atoms/NameTag/NameTag.tsx
  src/components/molecules/InputForm/InputForm.tsx
  src/components/templates/AlgoProblemForm.tsx
  src/components/templates/TrackProjectForm.tsx
  src/components/templates/WebGuideForm.tsx
  src/hooks/useCreateWebGuide.tsx
  src/hooks/useFinaleBoard.ts
  src/hooks/useProjectDetail.ts
  src/pages/trackProject/TrackProjectBoardCreate.tsx
  src/pages/trackProject/TrackProjectBoardUpdate.tsx
  src/pages/trackProject/TrackProjectDetail.tsx
  src/pages/trackProject/TrackProjectList.tsx
  src/stores/generationStore.ts
  src/stores/teamStore.ts
Labels: 🚧 Feature, 🎨 Markup

#138 [feat] 유튜브, 채팅, 비밀번호 변경 완료, 디바운스 유틸함수 추가
  src/App.tsx
  src/api/authAPI.ts
  src/components/atoms/Button/Button.tsx
  src/components/molecules/YoutubeCard/YoutubeCard.tsx
  src/components/organisms/BasicModal/BasicModal.tsx
  src/components/organisms/ChatSection/ChatSection.tsx
  src/components/organisms/StudentEditModal/StudentEditModal.tsx
  src/components/templates/WebConceptCards.tsx
  src/hooks/useChat.ts
  src/pages/ChangePassword.tsx
  src/pages/SignUp.tsx
  src/pages/admin/GenerationManagement.tsx
  src/pages/admin/StudentManagement.tsx
  src/pages/algorithmProblem/AlgorithmProblemCreate.tsx
  src/pages/algorithmProblem/AlgorithmProblemUpdate.tsx
  src/pages/index.tsx
  src/pages/music/PlayList.tsx
  src/pages/music/SearchMusic.tsx
  src/pages/webGuide/WebGuideCreate.tsx
  src/pages/webGuide/WebGuideUpdate.tsx
  src/pages/webRecommend/WebRecommendCreate.tsx
  src/stores/modalStore.ts
  src/utils/authService.ts
  src/utils/debounce.ts
  src/utils/submitKeyDownEnter.ts
  vite.config.ts
Labels: 🚧 Feature, 🛠️ Refactor

#141 [markup] 웹 학습 사이트 상세, 작성, 수정, 리스트 페이지 마크업
  src/api/WebRecommendAPI.ts
  src/components/molecules/WebSiteCard/WebSiteCard.stories.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.tsx
  src/components/templates/WebRecommendCards.tsx
  src/hooks/useContentDetail.ts
  src/pages/webRecommend/WebRecommendCreate.tsx
  src/pages/webRecommend/WebRecommendDetail.tsx
  src/pages/webRecommend/WebRecommendUpdate.tsx
Labels: 🚧 Feature, 🎨 Markup

#144 [feat] 알고리즘 문제 리스트 페이지, 알고리즘 풀이 리스트 페이지 구현
  src/api/AlgorithmProblemAPI.ts
  src/api/AlgorithmSolutionAPI.ts
  src/components/atoms/SelectOption/SelectOption.tsx
  src/components/molecules/AlgoDetailCard/AlgoDetailCard.tsx
  src/components/molecules/FilterChip/FilterChip.tsx
  src/components/templates/AlgoDetailCards.tsx
  src/components/templates/AlgoProblemCards.tsx
  src/components/templates/Skeletons/AlgoDetailCardSkeletonList.tsx
  src/components/templates/index.ts
  src/pages/algorithmProblem/AlgorithmProblemDetail.tsx
  src/pages/algorithmProblem/AlgorithmProblemList.tsx
  src/pages/algorithmSolution/AlgorithmSolutionCreate.tsx
Labels: 🚧 Feature, 🎨 Markup

#146 [Feat] 관통 프로젝트 일지 상세 조회 페이지 구현
  src/components/templates/ProjectBoardForm.tsx
  src/hooks/useProjectBoardDetail.tsx
  src/pages/trackProject/TrackProjectBoardDetail.tsx
Labels: 🚧 Feature, 🎨 Markup

#148 [feat] 북마크 추가삭제 구현, 알고리즘 풀이 디테일 AlgoInfo 수정, api 반환타입 명세서에 맞게 수정
  src/api/AlgorithmGuideAPI.ts
  src/api/bookmarkAPI.ts
  src/api/finaleAPI.ts
  src/api/mypageAPI.ts
  src/api/trackAPI.ts
  src/components/atoms/CalendarTag/CalendarTag.tsx
  src/components/molecules/AlgoInfo/AlgoInfo.tsx
  src/components/molecules/Title/Title.tsx
  src/components/molecules/WebSiteCard/WebSiteCard.tsx
  src/components/templates/AlgoProblemCards.tsx
  src/components/templates/AlgorithmGuideCards.tsx
  src/components/templates/BMAlgorithmGuideCards.tsx
  src/components/templates/BMAlgorithmSolutionCards.tsx
  src/components/templates/BMWebGuideCards.tsx
  src/components/templates/BMWebRecommendCards.tsx
  src/components/templates/WebConceptCards.tsx
  src/components/templates/WebRecommendCards.tsx
  src/components/templates/index.ts
  src/hooks/useContentDetail.ts
  src/hooks/useContentList.ts
  src/hooks/useGetBookmarkList.ts
  src/pages/algorithmGuide/AlgorithmGuideDetail.tsx
  src/pages/algorithmSolution/AlgorithmSolutionDetail.tsx
  src/pages/finalProject/FinalProjectList.tsx
  src/pages/mypage/bookmark/BMAlgorithmConcept.tsx
  src/pages/mypage/bookmark/BMAlgorithmSolution.tsx
  src/pages/mypage/bookmark/BMWebConcept.tsx
  src/pages/mypage/bookmark/BMWebRecommend.tsx
  src/pages/trackProject/TrackProjectList.tsx
  src/pages/webGuide/WebGuideDetail.tsx
  src/pages/webRecommend/WebRecommendDetail.tsx
  src/types/AlgorithmSolution.ts
  src/types/Bookmark.ts
  src/types/FinaleProject.ts
  src/types/TrackProject.ts
  src/utils/convertDate.ts
Labels: 🚧 Feature, 🛠️ Refactor

#149 [Refactor] 알고리즘 문제 수정 시 알고리즘 분류 초기 설정 / 웹 개념 수정 시 제목 초기 설정
  src/pages/algorithmProblem/AlgorithmProblemUpdate.tsx
  src/pages/webGuide/WebGuideUpdate.tsx
  src/pages/webRecommend/WebRecommendUpdate.tsx
Labels: 🛠️ Refactor

#150 [refactor] 알고리즘, 웹 관련 검색 기능 리팩토링
  src/api/AlgorithmGuideAPI.ts
  src/api/AlgorithmProblemAPI.ts
  src/components/templates/AlgoProblemCards.tsx
  src/components/templates/AlgorithmGuideCards.tsx
  src/components/templates/WebConceptCards.tsx
  src/components/templates/WebRecommendCards.tsx
Labels: 🛠️ Refactor

#161 [docs] CICD를 위한 main.yml 파일 생성
  .github/workflows/main.yml
Labels: 🌎 Deploy, 📑 Docs

#163 [docs] main.yml 수정
  .github/workflows/main.yml
Labels: 📑 Docs

#151 [Refactor] 일정 버그 및 그 외 코드 수정
  src/api/trackAPI.ts
  src/hooks/useAlgorithmTag.ts
  src/hooks/useSchedule.ts
  src/hooks/useScheduleEvents.ts
  src/pages/Schedule.tsx
  src/pages/algorithmProblem/AlgorithmProblemCreate.tsx
  src/pages/trackProject/TrackProjectBoardDetail.tsx
Labels: ❌ Bug, 🛠️ Refactor

#165 [docs] Dockerfile 추가
  Dockerfile
Labels: 🌎 Deploy, 📑 Docs

#167 [fx] TrackProjectDetail 데이터 없으면 null 반환
  src/pages/trackProject/TrackProjectDetail.tsx
Labels: ❌ Bug

#171 [Feat] 알고리즘 문제 생성, 수정 페이지 API 연결
  src/api/AlgorithmTagAPI.ts
  src/api/finaleAPI.ts
  src/api/trackAPI.ts
  src/components/molecules/SearchBar/SearchBar.tsx
  src/components/organisms/SearchTeamMember/SearchTeamMember.tsx
  src/components/templates/AlgoProblemForm.tsx
  src/components/templates/TrackProjectCards.tsx
  src/hooks/useAlgorithmTag.ts
  src/hooks/useProjectDetail.ts
  src/pages/algorithmProblem/AlgorithmProblemCreate.tsx
  src/pages/algorithmProblem/AlgorithmProblemUpdate.tsx
  src/pages/trackProject/TrackProjectDetail.tsx
  src/types/Tag.ts
  src/types/TrackProject.ts
Labels: 🚧 Feature, 🛠️ Refactor

#173 [Refactor] 관통 프로젝트 상세, 일지 작성, 수정 리팩토링
  src/api/trackAPI.ts
  src/components/organisms/ProjectCard/ProjectCard.tsx
  src/components/templates/TrackProjectCards.tsx
  src/pages/trackProject/TrackProjectBoardCreate.tsx
  src/pages/trackProject/TrackProjectBoardUpdate.tsx
  src/pages/trackProject/TrackProjectDetail.tsx
Labels: 🛠️ Refactor

#186 [fix] 웹 개념 글 작성/수정/삭제 권한 재설정
  src/api/WebGuideAPI.ts
  src/components/organisms/ProjectCard/ProjectCard.tsx
  src/pages/webGuide/WebGuideCreate.tsx
  src/pages/webGuide/WebGuideDetail.tsx
  src/pages/webGuide/WebGuideList.tsx
  src/pages/webGuide/WebGuideUpdate.tsx
Labels: ❌ Bug

#187 [fix] TrackProjectDetailResponse 필드명 수정
  src/pages/trackProject/TrackProjectDetail.tsx
  src/types/TrackProject.ts
Labels: ❌ Bug

#190 [Fix] 관통 프로젝트 디테일 제출현황, Breadcrumb 수정 / 작성자, 관리자 여부에 따른 버튼 유무 / 관리자 계정은 네비게이션에서 기수 표시 제거 / 학생 기수 변경 버그 해결
  src/App.tsx
  src/api/AlgorithmSolutionAPI.ts
  src/components/atoms/Persona/Persona.tsx
  src/components/molecules/AlgoInfo/AlgoInfo.tsx
  src/components/molecules/Title/Title.tsx
  src/components/organisms/Navigation/Navigation.tsx
  src/components/organisms/StudentEditModal/StudentEditModal.tsx
  src/components/organisms/SubmitSection/SubmitSection.tsx
  src/components/templates/AlgorithmSolutionForm.tsx
  src/hooks/useStudentEdit.ts
  src/pages/admin/StudentManagement.tsx
  src/pages/algorithmProblem/AlgorithmProblemDetail.tsx
  src/pages/algorithmSolution/AlgorithmSolutionCreate.tsx
  src/pages/algorithmSolution/AlgorithmSolutionDetail.tsx
  src/pages/algorithmSolution/AlgorithmSolutionUpdate.tsx
  src/pages/trackProject/TrackProjectBoardDetail.tsx
  src/pages/trackProject/TrackProjectCreate.tsx
  src/pages/trackProject/TrackProjectDetail.tsx
  src/types/AlgorithmProblem.ts
  src/utils/calcRouteStructure.ts
Labels: ❌ Bug

#196 [refactor] 반응형 말고 고정 너비로 레이아웃 수정
  src/api/mypageAPI.ts
  src/components/organisms/Navigation/Navigation.tsx
  src/components/templates/AlgoDetailCards.tsx
  src/components/templates/BMAlgorithmGuideCards.tsx
  src/components/templates/BMAlgorithmSolutionCards.tsx
  src/hooks/useGetBookmarkList.ts
  src/layouts/MainLayout.tsx
  src/pages/mypage/algorithm/MyAlgorithm.tsx
  src/pages/mypage/bookmark/BMAlgorithmConcept.tsx
  src/pages/mypage/bookmark/BMAlgorithmSolution.tsx
  src/pages/mypage/bookmark/BMWebConcept.tsx
  src/pages/mypage/bookmark/BMWebRecommend.tsx
  src/pages/mypage/project/MyTrackProject.tsx
Labels: 🛠️ Refactor, 🎨 Markup

#197 [style] 모든 리스트 페이지 내부 영역 고정 넓이로 레이아웃 수정
  src/components/templates/AlgoDetailCards.tsx
  src/components/templates/AlgoProblemCards.tsx
  src/components/templates/AlgorithmGuideCards.tsx
  src/components/templates/FinalListCard.tsx
  src/components/templates/FinalProjectDetailCards.tsx
  src/components/templates/TrackProjectCards.tsx
  src/components/templates/WebRecommendCards.tsx
  src/pages/finalProject/FinalProjectList.tsx
  src/pages/music/SearchMusic.tsx
  src/pages/trackProject/TrackProjectDetail.tsx
  src/pages/trackProject/TrackProjectList.tsx
Labels: 🎨 Markup

#199 [refactor] 북마크 리스트 구현
  src/api/mypageAPI.ts
  src/components/organisms/ProjectCard/ProjectCard.tsx
  src/components/templates/BMAlgorithmGuideCards.tsx
  src/components/templates/BMAlgorithmSolutionCards.tsx
  src/components/templates/BMWebGuideCards.tsx
  src/components/templates/BMWebRecommendCards.tsx
  src/hooks/useGetBookmarkList.ts
  src/pages/finalProject/FinalProjectList.tsx
  src/types/AlgorithmSolution.ts
Labels: 🛠️ Refactor

#195 [feat] myTrackList 구현
  src/components/templates/MyTrackProjectList.tsx
Labels: 🚧 Feature

#202 [Fix] 마이페이지 알고리즘, 트랙리스트 수정 / 모든 파일 console.log 삭제
  src/api/AlgorithmProblemAPI.ts
  src/api/mypageAPI.ts
  src/api/youtubeAPI.ts
  src/components/atoms/SelectOption/SelectOption.stories.tsx
  src/components/templates/BMAlgorithmGuideCards.tsx
  src/components/templates/BMAlgorithmSolutionCards.tsx
  src/components/templates/BMWebGuideCards.tsx
  src/components/templates/BMWebRecommendCards.tsx
  src/components/templates/FinalProjectDetailCards.tsx
  src/components/templates/MyAlgorithmList.tsx
  src/components/templates/MyFinalProjectList.tsx
  src/components/templates/MyTrackProjectList.tsx
  src/components/templates/TrackProjectCards.tsx
  src/components/templates/WebRecommendCards.tsx
  src/hooks/useContentDetail.ts
  src/hooks/useMyPage.ts
  src/layouts/MainLayout.tsx
  src/pages/ChangePassword.tsx
  src/pages/music/PlayList.tsx
  src/pages/music/SearchMusic.tsx
  src/types/AlgorithmSolution.ts
  src/types/Bookmark.ts
  src/types/TrackProject.ts
  src/utils/pdf/parseMarkdown.tsx
Labels: ❌ Bug, 🛠️ Refactor

#203 [refactor] 북마크 완료
  src/components/templates/BMAlgorithmGuideCards.tsx
  src/components/templates/BMAlgorithmSolutionCards.tsx
  src/components/templates/BMWebGuideCards.tsx
  src/components/templates/BMWebRecommendCards.tsx
  src/components/templates/FinalListCard.tsx
  src/components/templates/TrackProjectCards.tsx
  src/pages/trackProject/TrackProjectDetail.tsx
  src/pages/trackProject/TrackProjectList.tsx
Labels: 🚧 Feature, 🛠️ Refactor, 🎨 Markup

#209 [fix] 회원가입 유효성 검증 메세지 기능 수정
  src/api/authAPI.ts
  src/hooks/useSignUp.ts
  src/pages/SignUp.tsx
Labels: 🚧 Feature

#214 [feat] MyFinalProjectList 구현
  src/components/templates/MyFinalProjectList.tsx
Labels: 🚧 Feature

#216 [Fix] 일정 관련 모든 오류사항 수정/알고리즘 문제 url 중복 확인
  src/api/scheduleAPI.ts
  src/hooks/useScheduleEvents.ts
  src/pages/Schedule.tsx
  src/pages/algorithmProblem/AlgorithmProblemCreate.tsx
  src/pages/algorithmProblem/AlgorithmProblemUpdate.tsx
  src/types/Schedule.ts
Labels: ❌ Bug

#218 [feat]: 관통 프로젝트 수정, 팀 생성, 팀 수정 구현 및 리팩토링
  src/api/trackAPI.ts
  src/components/molecules/index.ts
  src/components/templates/TrackProject.tsx
  src/components/templates/TrackProjectTeam.tsx
  src/pages/trackProject/TrackProjectCreate.tsx
  src/pages/trackProject/TrackProjectTeamCreate.tsx
  src/pages/trackProject/TrackProjectTeamUpdate.tsx
  src/pages/trackProject/TrackProjectUpdate.tsx
Labels: 🚧 Feature

#219 [refactor] PDF key값 누락 문제 해결, 마이페이지 파이널 수정
  src/api/mypageAPI.ts
  src/components/templates/BMAlgorithmSolutionCards.tsx
  src/components/templates/FinalListCard.tsx
  src/components/templates/MyFinalProjectList.tsx
  src/components/templates/MyTrackProjectList.tsx
  src/hooks/useProjectBoardDetail.tsx
  src/types/FinaleProject.ts
  src/utils/pdf/parseMarkdown.tsx
Labels: 🛠️ Refactor

#220 fix] 알고리즘 풀이 수정 시 기존 작성한 언어 렌더링
  src/pages/algorithmSolution/AlgorithmSolutionUpdate.tsx
Labels: 🛠️ Refactor

#221 [fix] 페이지 접근 권한 및 에러 모달창 추가 / SubmitSection 라우팅 방식 변경
  src/api/AlgorithmGuideAPI.ts
  src/api/WebRecommendAPI.ts
  src/components/molecules/TeamTag/TeamTag.tsx
  src/components/organisms/SubmitSection/SubmitSection.tsx
  src/components/templates/AlgorithmGuideForm.tsx
  src/hooks/useScheduleEvents.ts
  src/pages/algorithmGuide/AlgorithmGuideCreate.tsx
  src/pages/algorithmGuide/AlgorithmGuideDetail.tsx
  src/pages/algorithmGuide/AlgorithmGuideUpdate.tsx
  src/pages/algorithmProblem/AlgorithmProblemCreate.tsx
  src/pages/algorithmProblem/AlgorithmProblemUpdate.tsx
  src/pages/algorithmSolution/AlgorithmSolutionUpdate.tsx
  src/pages/finalProject/FinalProjectBoardCreate.tsx
  src/pages/finalProject/FinalProjectBoardUpdate.tsx
  src/pages/finalProject/FinalProjectDetail.tsx
  src/pages/finalProject/FinalProjectList.tsx
  src/pages/trackProject/TrackProjectBoardCreate.tsx
  src/pages/trackProject/TrackProjectBoardUpdate.tsx
  src/pages/trackProject/TrackProjectDetail.tsx
  src/pages/webGuide/WebGuideCreate.tsx
  src/pages/webGuide/WebGuideUpdate.tsx
  src/pages/webRecommend/WebRecommendCreate.tsx
  src/pages/webRecommend/WebRecommendUpdate.tsx
Labels: ❌ Bug

#225 [refactor] 비밀번호 변경 valid에러 출력 및 재발송 로직 구현
  README.md
  public/readme/1로그인.png
  public/readme/2일정관리.png
  public/readme/3-0관통프로젝트.png
  public/readme/3-1관통프로젝트디테일.png
  public/readme/4파이널프로젝트.png
  public/readme/5알고리즘.png
  public/readme/6웹.png
  public/readme/7음악.png
  public/readme/8학생관리.png
  public/readme/9기수관리.png
  src/api/authAPI.ts
  src/components/organisms/EmailVerificationModal/EmailVerificationModal.tsx
  src/main.tsx
  src/pages/ChangePassword.tsx
Labels: 🛠️ Refactor

#227 [fix]: 파이널 프로젝트 수정 관련 로직 추가, 빈 페이지 삭제
  src/App.tsx
  src/pages/finalProject/FinalProjectTeamUpdate.tsx
  src/pages/finalProject/FinalProjectUpdate.tsx
  src/pages/index.tsx
Labels: ❌ Bug

#228 [deploy]
  src/App.tsx
  src/pages/finalProject/FinalProjectTeamUpdate.tsx
  src/pages/finalProject/FinalProjectUpdate.tsx
  src/pages/index.tsx
Labels: 🌎 Deploy

#229 [refactor] chat 부분 리스트 null 처리
  src/api/chatAPI.ts
  src/components/organisms/ChatSection/ChatSection.tsx
  src/components/organisms/EmailVerificationModal/EmailVerificationModal.tsx
  src/components/organisms/PlayListSection/PlayListSection.tsx
  src/components/templates/FinalListCard.tsx
  src/components/templates/MyTrackProjectList.tsx
  src/hooks/useChat.ts
  src/pages/ChangePassword.tsx
  src/pages/algorithmGuide/AlgorithmGuideCreate.tsx
  src/pages/algorithmGuide/AlgorithmGuideUpdate.tsx
  src/pages/music/SearchMusic.tsx
Labels: 🛠️ Refactor

#230 [deploy] chat 부분 리스트 null 처리
  src/api/chatAPI.ts
  src/components/organisms/ChatSection/ChatSection.tsx
  src/components/organisms/EmailVerificationModal/EmailVerificationModal.tsx
  src/components/organisms/PlayListSection/PlayListSection.tsx
  src/components/templates/FinalListCard.tsx
  src/components/templates/MyTrackProjectList.tsx
  src/hooks/useChat.ts
  src/pages/ChangePassword.tsx
  src/pages/algorithmGuide/AlgorithmGuideCreate.tsx
  src/pages/algorithmGuide/AlgorithmGuideUpdate.tsx
  src/pages/music/SearchMusic.tsx
Labels: 🌎 Deploy
